name: attendance_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  collection: ^1.18.0  # Or a version compatible with your other dependencies.
  intl: ^0.17.0
  camera: ^0.11.0+2
  http: ^1.2.2
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  sqflite: ^2.4.0
  uuid: ^4.5.1
  path: ^1.8.0
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  image: ^4.3.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  logger: ^2.4.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  dropdown_search: ^6.0.1
  file_picker: ^8.1.4 
  dio: ^5.7.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  device_info_plus: ^11.1.1
  pdf: ^3.11.1
  printing: ^5.13.4
  syncfusion_flutter_charts: ^21.2.4
  tree_view_flutter: ^1.0.2
  org_chart: ^1.0.1
  lucide_icons: ^0.257.0
  flutter_image_compress: ^2.3.0
  retry: ^3.1.2
  badges: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 

flutter:
  uses-material-design: true

 